[[redirects]]
from = "/sitemap.xml"
to = "https://mypuvkzsgwanilduniup.supabase.co/functions/v1/sitemap"
status = 200
force = true

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[build]
command = "npx vite build"
publish = "dist"
